### ISSUE TITLE
kitty에서 갈아탈 만 한가요?

### ISSUE THREAD

**Issue by devilofdev** [hwhang0917/wezterm#1]
좋아보입니닷

**Comment by hwhang0917** [comment]
지금 윈도우 환경에서 개발하게 되어서 kitty를 못 쓰게 됐는데 쓰다 보니 괜찮아서 갈아타려 합니다 ㅎㅎ
neovim 처럼 설정파일을 lua로 할 수 있어서 kitty 보다 프로그래밍적으로 커스텀 할 수 있는 요소가 많아서 좋습니다.
